#ifndef CNC_PINOUT_H
#define CNC_PINOUT_H

#define X_LINIAR_MOTOR_PULSE_PIN
#define X_LINIAR_MOTOR_DIRECTION_PIN

#define Y_LINIAR_MOTOR_PULSE_PIN
#define Y_LINIAR_MOTOR_DIRECTION_PIN

#define Z_LINIAR_MOTOR_PULSE_PIN
#define Z_LINIAR_MOTOR_DIRECTION_PIN

#define X_ROTATION_MOTOR_PULSE_PIN
#define X_ROTATION_MOTOR_DIRECTION_PIN

#define Y_ROTATION_MOTOR_PULSE_PIN
#define Y_ROTATION_MOTOR_DIRECTION_PIN

#define CNC_SPINDLE_PIN

#endif